#/gps/ang/type iso
#/gps/ang/mintheta 0 deg
#/gps/ang/minphi 0 deg
#/gps/ang/maxtheta -90 deg
#/gps/ang/maxphi 360 deg

# CONE SHAPE 
#/gps/ang/mintheta 45 deg
#/gps/ang/minphi -135 deg
#/gps/ang/maxtheta 135 deg
#/gps/ang/maxphi -45 deg

/gps/direction 0 1 0
#/gps/pos/type Plane
#/gps/pos/shape Circle
#/gps/pos/radius 1 mm
#/gps/pos/rot1 1 0 0
#/gps/pos/rot2 0 0 1

/gps/particle mu-
/gps/pos/centre 0. 0. 0. cm

/gps/energy 10 MeV
/run/beamOn 1000

